### ISSUE TITLE
Script for Item-search on Ebay via API [$125 awarded]

### ISSUE THREAD

**Issue by fropl** [mercatos/Ebay#1]
Preferred programming language: **Python**, Rust... php
**API keys will be provided...**

It is required to write a script to search for Items (products) on ebay by keyword & using filters (condition, buyingOption, Country of Item Location ...) . The script must use the method specified in the Ebay API https://developer.ebay.com/api-docs/buy/browse/resources/item_summary/methods/search and **return the results in JSON Format (Item ID, Item Title, Price, Condition, buyingOption, URL)!** 

We can also set the maximum number of Items (products) that we want to receive in 1 request (for example, only the first 15 products)

**Netx step:** The second step is to get detailed information about the products found and output this information in json - **[please see issue](https://github.com/mercatos/Ebay/issues/2)**

**Comment by abcpro1** [comment]
~Hi. I'll make you a script in python, rust, php or nodejs if i can get an API key for testing.~

**Comment by fropl** [comment]
> Hi. I'll make you a script in python, rust, php or nodejs if i can get an API key for testing.

Hi and thanks for your interest! **Prefer python!**

Yes, sure. Please contact me on telegram https://t.me/mercatos and I will provide the data!

**Comment by i-mighty** [comment]
Any reservations against Nodejs?

**Comment by abcpro1** [comment]
It looks like there are people interested, so I concede this task to anyone willing to take it.

**Comment by fropl** [comment]
> Any reservations against Nodejs?

Hi & Thank you! Unfortunately, the solution in this language does not suit us. There may be other tasks and I will gladly contact you.

**Comment by fropl** [comment]
> It looks like there are people interested, so I concede this task to anyone willing to take it.

Good afternoon  - this task is still open!

**Comment by cryptomadvad** [comment]
Hi @fropl is this task still open?

**Comment by fropl** [comment]
> Good afternoon - this task is still open!

Good afternoon - this task is still open!

**Comment by cryptomadvad** [comment]
@fropl Script is ready, how can I submit it? I messages you in Telegram

**Comment by fropl** [comment]
> @fropl Script is ready, how can I submit it? I messages you in Telegram

Great news - thanks!

Please make a Pull request.

**Comment by cryptomadvad** [comment]
> > @fropl Script is ready, how can I submit it? I messages you in Telegram
> 
> Great news - thanks!
> 
> Please make a Pull request.

https://github.com/mercatos/Ebay/pull/4 here is the PR
