### ISSUE TITLE
Script for get detailed Product-Information on Ebay via API by item-id [$100 awarded]

### ISSUE THREAD

**Issue by fropl** [mercatos/Ebay#2]
Preferred programming language: **Python**, Rust... php
**API keys will be provided...**

It is required to write a script to get detailed information about products on ebay through the API by item-id (
  https://developer.ebay.com/api-docs/buy/browse/resources/item/methods/getItem The received information should be output in JSON format.

**Mandatory information you need to get about the product:**

- product.title
- product.description
- product.brand
- product.gtins
- product.image
- product.mpns
- itemLocation
- price + Currency
- buyingOption
- condition
- maybe a few more...

**Comment by ThakurKarthik** [comment]
@fropl Can we work on this independent of #1 ? If yes, I am up for picking this task.

**Comment by fropl** [comment]
> 

Hi and thanks for your interest! No problem!

Please contact me on telegram and I will provide data for API!

**Comment by jnguyen0220** [comment]
Please provide api key and item-id

**Comment by fropl** [comment]
> Please provide api key and item-id

Good afternoon!

Here are a few ids for example (I hope you understand that the script should work for a large number of other products?) : 175089549401, 175354550208

Please contact me on telegram https://t.me/mercatos and I will provide the data!

p.s. or can i provide sandbox data?

**Comment by jnguyen0220** [comment]
What about the api key?. The item id will be dynamic just need item id for testing.

**Comment by ArtemGr** [comment]
There's a working base64 sandbox key at
https://github.com/ThakurKarthik/Ebay/blob/177b828c0b2f6951fa1e64505fc1c8e0ce649643/ebay-apis/clientCredentials.py#L19

We could use some help converting the URL IDs, such as 175089549401 in https://www.ebay.com/itm/175089549401, into API IDs.

**Comment by jnguyen0220** [comment]
@ArtemGr: can you point to the documentation for it?. I am able to get it going but for some reason the provided item id is not valid.
